### ISSUE TITLE
Custom styles documentation is wrong

### ISSUE THREAD

**Issue by mugan86** [compodoc/website#12]
In the following content, there is an erratum that gives problems in the menu (the icons disappear) and the operation of the drop-down is incorrect

This content is not correct.
Inside your folder you need to provide at least a style.css file with **these 5** imports as below.

```
@import "./reset.css";
@import "./bootstrap.min.css";
@import "./bootstrap-card.css";
@import "./font-awesome.min.css";
@import "./compodoc.css";
@import "./prism.css";
@import "./tablesort.css";
```

I have tested with the following imports and the operation is satisfactory
```
@import "./reset.css";
@import "./bootstrap.min.css";
@import "./bootstrap-card.css";
@import "./prism.css";
@import "./ionicons.min.css";
@import "./compodoc.css";
@import "./tablesort.css";
```
The key is in the theme of the icons, it does not load the css file of the fotawesome and if the ionic icons, so I used that (based on the result of the generation with the default settings)

**Comment by vogloblinsky** [comment]
Fixed by #13
